### ISSUE TITLE
Installing on a fresh Ubuntu18.04 using pip3

### ISSUE THREAD

**Issue by ddetommaso** [hoechenberger/questplus#33]
I get the following output

```
Collecting questplus
  Using cached https://files.pythonhosted.org/packages/ec/a4/8d47d76a484e0f7080cd43b3141063efd938a7aceb8a2bc39fe2dc08685a/questplus-0.0.5.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-llc0eh02/questplus/setup.py", line 12, in <module>
        version=versioneer.get_version(),
      File "/tmp/pip-build-llc0eh02/questplus/versioneer.py", line 1480, in get_version
        return get_versions()["version"]
      File "/tmp/pip-build-llc0eh02/questplus/versioneer.py", line 1412, in get_versions
        cfg = get_config_from_root(root)
      File "/tmp/pip-build-llc0eh02/questplus/versioneer.py", line 344, in get_config_from_root
        parser.readfp(f)
      File "/usr/lib/python3.6/configparser.py", line 763, in readfp
        self.read_file(fp, source=filename)
      File "/usr/lib/python3.6/configparser.py", line 718, in read_file
        self._read(f, source)
      File "/usr/lib/python3.6/configparser.py", line 1015, in _read
        for lineno, line in enumerate(fp, start=1):
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 46: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-llc0eh02/questplus/

```

**Comment by hoechenberger** [comment]
This seems to be an issue of distutils having trouble to deal with non-ASCII characters in `setup.cfg`, see https://github.com/pypa/setuptools/issues/1062

Could you try to install via:
```
LC_ALL=en_US.UTF-8 pip install -U questplus
```

**Comment by ddetommaso** [comment]
Hi @hoechenberger ,

thank you for your answer! It worked for me!

**Comment by hoechenberger** [comment]
Great! The obvious fix would be to remove the umlaut (in my last name) from setup.cfg, as long as setuptools is struggling with this under some circumstances. But I‘d rather not mutilate my name ;) So I’ll just leave things unchanged for now but will leave this issue open for future reference. I’m open to further suggestions though!

**Comment by hoechenberger** [comment]
This should be resolved now with the latest version of setuptools.
