### ISSUE TITLE
It looks like QuestPlus isn't working with numpy>=1.24 when setting priors

### ISSUE THREAD

**Issue by peircej** [hoechenberger/questplus#50]
This example in psychopy code:

``` python
from questplus import QuestPlus
import numpy as np

thresholds = np.arange(-40, 0 + 1)
slope, guess, lapse = 3.5, 0.5, 0.02
contrasts = thresholds.copy()

threshold_prior_vals = np.random.randint(low=1, high=10,
                                        size=len(thresholds))
threshold_prior_vals = threshold_prior_vals / threshold_prior_vals.sum()
prior = dict(threshold=threshold_prior_vals)
q = QuestPlusHandler(
    nTrials=20,
    intensityVals=contrasts,
    thresholdVals=thresholds,
    slopeVals=slope,
    lowerAsymptoteVals=guess,
    lapseRateVals=lapse,
    prior=prior)
print (q)
```
results in this error with numpy 1.24 but succeeds in numpy <=1.23

```
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/lpzjwp/Desktop/questplus_test.py", line 14, in <module>
    q = QuestPlusHandler(
  File "/Users/lpzjwp/code/psychopy/git/psychopy/data/staircase.py", line 1575, in __init__
    self._qp = qp.QuestPlusWeibull(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/questplus/qp.py", line 489, in __init__
    super().__init__(stim_domain=dict(intensity=intensities),
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/questplus/qp.py", line 86, in __init__
    self.prior = self._gen_prior(prior=prior)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/questplus/qp.py", line 175, in _gen_prior
    prior_grid = np.meshgrid(*list(prior_orig.values()),
  File "<__array_function__ internals>", line 200, in prod
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 3076, in prod
    return _wrapreduction(a, np.multiply, 'prod', axis, dtype, out,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.
```

**Comment by hoechenberger** [comment]
Hello @peircej, I cannot reproduce this with NumPy 1.24.2, neither with "pure" QuestPlus:

```python
from questplus import QuestPlusWeibull
import numpy as np

thresholds = np.arange(-40, 0 + 1)
slope, guess, lapse = 3.5, 0.5, 0.02
contrasts = thresholds.copy()

threshold_prior_vals = np.random.randint(low=1, high=10,
                                        size=len(thresholds))
threshold_prior_vals = threshold_prior_vals / threshold_prior_vals.sum()
prior = dict(threshold=threshold_prior_vals)


q = QuestPlusWeibull(
    thresholds=thresholds,
    intensities=contrasts,
    slopes=slope,
    lower_asymptotes=guess,
    lapse_rates=lapse,
    prior=prior
)
```
nor with PsychoPy's `QuestPlusHandler`:
```python
from psychopy.data import QuestPlusHandler
import numpy as np

thresholds = np.arange(-40, 0 + 1)
slope, guess, lapse = 3.5, 0.5, 0.02
contrasts = thresholds.copy()

threshold_prior_vals = np.random.randint(low=1, high=10,
                                        size=len(thresholds))
threshold_prior_vals = threshold_prior_vals / threshold_prior_vals.sum()
prior = dict(threshold=threshold_prior_vals)
q = QuestPlusHandler(
    nTrials=20,
    intensityVals=contrasts,
    thresholdVals=thresholds,
    slopeVals=slope,
    lowerAsymptoteVals=guess,
    lapseRateVals=lapse,
    prior=prior)
print (q)
```

**Comment by hoechenberger** [comment]
@peircej Could you please check which version of `xarray` you're using? Maybe this is what makes the difference

**Comment by peircej** [comment]
Ah! It's working in questplus dev! If you could make a new release I think we're done! 😁

**Comment by hoechenberger** [comment]
Ha!!! Super good catch, Jon! I will draft a new release ASAP. Please do poke me if nothing's happens by the end of this week

Best wishes

**Comment by hoechenberger** [comment]
I just published a new release to PyPI. Thanks for the pointer, Jon!
